package com.esipovich.challenge.find_the_difference;

/**
 * @author Artem Esipovich 5/24/2018
 *
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 */

public class FindTheDifference {

    public static void main(String[] args) {
        System.out.println(findTheDifference("abcd", "abcde") + " is the letter that was added");
    }

    private static char findTheDifference(String firstString, String secondString) {
        for (int i = 0; i < firstString.length(); i++){
            secondString = secondString.replaceFirst(String.valueOf(firstString.charAt(i)), "");
        }
        return secondString.charAt(0);
    }
}
